import json
import os
from datetime import datetime

def generate_report():
    print("[!] PurpleGuard: Generating Executive Security Report...")
    try:
        with open("public/metadata.json", "r") as f:
            data = json.load(f)
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        report_name = f"PurpleGuard_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
        
        report_content = f"""# 🛡️ PurpleGuard Executive Security Report
**Date:** {timestamp}
**Target Status:** COMPROMISED
**Total Confirmed Kills:** {data.get('total_kills', 0)}

---

## 🧠 AI Strategic Analysis (Hephaestus)
{data.get('ai_analysis', 'No analysis available.')}

---

## 🧬 Evolutionary Ammunition (RedBrain)
The following mutated payloads were generated to bypass existing WAF/IDS filters:
{chr(10).join([f"- `{p}`" for p in data.get('mutated_payloads', [])])}

---

## 🚀 Telemetry Feed (Top Findings)
| Type | Target URL |
| :--- | :--- |
"""
        for finding in data.get('findings', [])[:10]:
            report_content += f"| {finding['type']} | {finding['target']} |\n"

        report_content += "\n\n**Note:** This report was autonomously generated by the PurpleGuard Neural Evolution Engine."

        # Save to local project and phone storage
        with open(report_name, "w") as rf:
            rf.write(report_content)
        
        # Export to Downloads if storage is linked
        storage_path = os.path.expanduser("~/storage/downloads/")
        if os.path.exists(storage_path):
            with open(os.path.join(storage_path, report_name), "w") as sf:
                sf.write(report_content)
            print(f"[+] Report exported to Phone Downloads: {report_name}")
        else:
            print(f"[+] Report saved locally: {report_name}")

    except Exception as e:
        print(f"[-] Report Error: {e}")

if __name__ == "__main__":
    generate_report()
